### ISSUE TITLE
Is this lib production ready?

### ISSUE THREAD

**Issue by abitdodgy** [nandosousafr/pagseguro_ex#3]
I'm wondering because it looks like it's no longer under active development. Did you ever use this in production?

**Comment by abitdodgy** [comment]
@nandosousafr sorry to bug you, but I'm wondering if you can answer my question...

**Comment by nsoufr** [comment]
Hi @abitdodgy, sorry for the delay.

I dont think is ready for production. It lacks lots of features! Actually, the only feature implemented is the payment creation. 

Also, there's a critical issue:
https://github.com/nandosousafr/pagseguro_ex/issues/1

If you want we definitely can work together to make it ready for production. I'm looking forward to work more on  OSS these days. If so, just submit the issues so we can reason about them together.

If you want to contact me directly my email is nandosousafr at gmail dot com
